include $(ZEPHYR_BASE)/tests/Makefile.test

obj-y = main.o test_suspendresume_lowpower.o
obj-y += common/test_powerstate.o
obj-y += common/test_suspendresume_sysdev.o
obj-y += common/test_suspendresume_sysclock.o
obj-y += common/test_suspendresume_rtc.o
obj-y += common/test_suspendresume_uart.o
obj-y += common/test_suspendresume_aonpt.o
