ccflags-y += -I${ZEPHYR_BASE}/tests/include

obj-$(CONFIG_DEVICE_POWER_MANAGEMENT) += test_sysdev_suspend.o
obj-$(CONFIG_SYS_POWER_DEEP_SLEEP) += main_suspend_resume_deepsleep.o
obj-$(CONFIG_SYS_POWER_LOW_POWER_STATE) += main_suspend_resume_lowpower.o
